# Generated by Django 4.2.4 on 2024-07-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'customer'), ('Staff', 'staff')], default='Customer', max_length=20),
        ),
    ]
