# Generated by Django 4.2.4 on 2024-07-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='In Transit', max_length=50),
        ),
    ]
