# Generated by Django 4.2.4 on 2024-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='departure_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
