# Generated by Django 4.2.4 on 2024-08-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shipment_has_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered')], default='Picked Up', max_length=50),
        ),
        migrations.AlterField(
            model_name='trackshipment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_shipments', to='main.shipment'),
        ),
    ]
