# Generated by Django 4.2.4 on 2024-08-27 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_from', models.CharField(blank=True, max_length=255)),
                ('shipped_to', models.CharField(blank=True, max_length=255)),
                ('departure_date', models.DateTimeField(auto_now_add=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Picked Up', 'Picked Up'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered')], default='In Transit', max_length=50)),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Picked Up', 'Picked Up'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered')], default='Picked Up', max_length=50)),
                ('tracking_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shipment')),
            ],
        ),
    ]
